local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>tf', builtin.find_files, {desc = "Search Files"})
vim.keymap.set('n', '<leader>tg', builtin.git_files, {desc = "Search git files"})
vim.keymap.set('n', '<leader>td', builtin.diagnostics, {desc = "Browse diagnostics"})
vim.keymap.set('n', '<leader>tr', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ")})
end, {desc = "Grep term"})
